export const RSA_PUBLIC_KEY = `
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyuPrmCxLw3sijgjZBEIV
5I9zDhS84UILsMBqeelWH6vOSOzCCp1vmwmSUULONEMMoF/l8dlbVDLg4tAxujwb
G9Skkp8d2JvozOFe/I/hutFaRGJOSnGVtcxeovlT1mTFulVKrSCbwyLUQVPOahC0
rzO3xUMp/SsJHmn/KhZyTW1/GTzneTT4MUJapdeFEMt0Q6gWuyE7Ap3Ryw78Kt4q
Kz9gmf6B2UZTX9/jgzAAw8hSK9jnk8rzT552lOEWumtj5CUaoYwLBEcJW6hyt+Zs
Ntzm/3/O2AX+oaSYw1C+kAEqhVwg7Lax87EaRNzJyUK7kkSSybhDL5/sbBxHVSuU
pwIDAQAB
-----END PUBLIC KEY-----
`;
